blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls',namespace = 'blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/post/urls.py
from . import views
from django.urls import path
app_name = 'post'
urlpatterns = [
    path('', views.all_posts, name = 'all_posts'),
    path('<int:id>/', views.post, name = 'post'),
    path('create/', views.create_post, name = 'create_post'),
    path('<int:id>/edit_post/', views.edit_post, name = 'edit_post'),
    path('<int:id>/delete_post/', views.delete_post, name = 'delete_post' ),
]
#

blog/post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete = 'None')
    title = models.CharField(max_length= 50)
    content = RichTextField()
    img = models.ImageField(upload_to = 'post_img/')
    created = models.DateTimeField(default = timezone.now())
    active = models.BooleanField(default = True)

    def __str__(self):
        return  self.title

blog/post/forms.py
from .models import Post
from django import forms
from ckeditor.widgets import CKEditorWidget

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = ['title','content','img']

blog/post/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .forms import PostForm
from .models import Post
from django.contrib import messages
# Create your views here.
def all_posts(request):
    all_posts = Post.objects.filter(active = True)
    context = {
        'all_posts' : all_posts,
    }
    return render(request, 'posts.html', context)

def post(request, id):
    post = get_object_or_404(Post ,id = id )
    context = {
        'post' : post,
    }
    return render(request, 'detail.html', context)

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES)
        if form.is_valid():
            new_form = form.save(commit = False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Post Created Successful.')
            return redirect('/')
    else:
        form = PostForm()

    return render(request, 'create.html', {'form':form})


def edit_post(request, id):
    post = get_object_or_404(Post, id = id)
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES, instance = post)
        if form.is_valid():
            new_form = form.save(commit = False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Post Edited Successfully.')
            return redirect('/')
    else:
        form = PostForm(instance = post)

    context = {
        'form' : form,
    }
    return render(request, 'edit.html', context)

def delete_post(request, id):
    post = get_object_or_404(Post, id = id)
    post.delete()
    messages.success(request,'Post Deleted Successfully.')
    return redirect('/')

blog/post/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href={% static "post/css/style.css" %}>
    <title>{{post}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url "blog:all_posts" %}">Python News</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

     </nav>
     <div class="message_div">
       {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
     </div>
     <div class="container">
       <div class="row mt-4">
         {% block body %}
         {% endblock body %}
         </div>

           </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

blog/post/templates/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="blog_form">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
  {% buttons %}
      <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}

  </form>
</div>

{% endblock body %}

blog/post/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="jumbotron banner">
  <a class="btn btn-primary btn-lg" href="{% url "blog:edit_post" post.id %}" role="button">Edit post</a>
  <a class="btn btn-primary btn-lg" href="{% url "blog:delete_post" post.id %}" role="button">Delete post</a>
</div>
           <div class="card single_post">
             {% if post.img %}
             <img class="card-img-top" src="{{post.img.url}}" alt="Card image cap">
             {% endif %}
             <div class="card-body">
               <h5 class="card-title">{{post.title}}</h5>
               <p class="card-text"> {{post.content|safe}}</p>
             </div>
           </div>
         </div>

           </div>
{% endblock body %}

blog/post/templates/edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="blog_form">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
  {% buttons %}
      <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}

  </form>
</div>

{% endblock body %}

blog/post/templates/posts.html
{% extends 'base.html' %}
{% block body %}
<div class="jumbotron banner">
  <a class="btn btn-primary btn-lg" href="{% url "blog:create_post" %}" role="button">Create post</a>
</div>
        {% for post in all_posts %}
         <div class="col-md-4">
           <div class="card">
             {% if post.img %}
             <img class="card-img-top" src="{{post.img.url}}" alt="Card image cap">
            {% endif %}
             <div class="card-body">
               <h5 class="card-title">{{ post.title }}</h5>
               <p class="card-text">{{ post.content|safe|truncatewords:10 }}</p>
               <a href="{% url 'blog:post' post.id %}" class="btn btn-primary">Read</a>
               <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-primary">Delete</a>
             </div>
           </div>
         </div>
         {% endfor %}


         </div>
       </div>
{% endblock body %}